<a href="https://colab.research.google.com/github/Muralikrishna019/Machine-Learning-Lab/blob/main/Lab1_(numpy)AP23110010656.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Create a rank 1 array
a = np.array([0, 1, 2])
print(type(a))
# this will print the dimension of the array
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
# Change an element of the array
a[0] = 5
print(a)
# Create a rank 2 array
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])


<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]
(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [ ]:
import numpy as np
# Create a rank 1 array
a = np.array([0, 1, 2])
print(type(a))
# this will print the dimension of the array
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
# Change an element of the array
a[0] = 5
print(a)
# Create a rank 2 array
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])
#Creating NumPy Array
#NumPy also provides many built-in functions to create arrays. The best way to learn this is
#through examples.
#Example 02: Creating NumPy array
# Create a 3x3 array of all zeros
a = np.zeros((3,3))
print(a)
# Create a 2x2 array of all ones
b = np.ones((2,2))
print(b)
# Create a 3x3 constant array
c = np.full((3,3), 7)
print(c)
# Create a 3x3 array filled with random values
d = np.random.random((3,3))
print(d)
# Create a 3x3 identity matrix
e = np.eye(3)
print(e)
# convert list to array
f = np.array([2, 3, 1, 0])
print(f)
# arange() will create arrays with regularly incrementing values
g = np.arange(20)
print(g)
# note mix of tuple and lists
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)
# create an array of range with float data type
i = np.arange(1, 8, dtype=float)
print(i)
# linspace() will create arrays with a specified number of items which are
# spaced equally between the specified beginning and end values j= np.linspace(start, stop, num)
j = np.linspace(2, 4, 5)
print(j)


<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]
(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.83363395 0.1595335  0.9479808 ]
 [0.48571362 0.69774189 0.70276538]
 [0.37836055 0.32558203 0.48572144]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]
[1. 2. 3. 4. 5. 6. 7.]
[2.  2.5 3.  3.5 4. ]


In [ ]:
# Let numpy choose the datatype
x = np.array([0, 1])
y = np.array([2.0, 3.0])
# Force a particular datatype
z = np.array([5, 6], dtype=np.int64)
print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [ ]:
import numpy as np
# An exemplar array
arr = np.array([[-1, 2, 0, 4],
 [4, -0.5, 6, 0],
 [2.6, 0, 7, 8],
 [3, -7, 4, 2.0]])
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [ ]:
# Python program to demonstrate
# basic operations on single array
import numpy as np

a = np.array([1, 2, 5, 3])

# add 1 to every element
print ("Adding 1 to every element:", a+1)

# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)

# multiply each element by 10
print ("Multiplying each element by 10:", a*10)

# square each element
print ("Squaring each element:", a**2)

# modify existing array
a *= 2
print ("Doubled each element of original array:", a)

# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])

print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [ ]:
# Python program to demonstrate
# unary operators in numpy
import numpy as np

arr = np.array([[1, 5, 6],
 [4, 7, 2],
 [3, 1, 9]])

# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))

# minimum element of array
print ("Column-wise minimum elements:",arr.min(axis = 0))

# sum of array elements
print ("Sum of all array elements:",arr.sum())

# cumulative sum along each row
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [ ]:
# Python program to demonstrate
# binary operators in Numpy
import numpy as np

a = np.array([[1, 2],
 [3, 4]])
b = np.array([[4, 3],
 [2, 1]])

# add arrays
print ("Array sum:\n", a + b)

# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)

# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [ ]:
# Python program to demonstrate
# universal functions in numpy
import numpy as np

# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))


Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [ ]:
##simple python program to find the inverse of an array (without exception handling)
import numpy as np
arr = np.array([[-1, 2, 0, 4],
 [4, -0.5, 6, 0],
 [2.6, 0, 7, 8],
 [3, -7, 4, 2.0]])
inverse = np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])

In [ ]:
import numpy as np
data = np.genfromtxt('fitness.txt', delimiter='\t', skip_header=1, dtype=None, encoding='utf-8')
# Print first few rows
print(data[:20])

[('06-10-2017', 5464, 200, 181, 5,   0, 66)
 ('07-10-2017', 6041, 100, 197, 8,   0, 66)
 ('08-10-2017',   25, 100,   0, 5,   0, 66)
 ('09-10-2017', 5461, 100, 174, 4,   0, 66)
 ('10-10-2017', 6915, 200, 223, 5, 500, 66)
 ('11-10-2017', 4545, 100, 149, 6,   0, 66)
 ('12-10-2017', 4340, 100, 140, 6,   0, 66)
 ('13-10-2017', 1230, 100,  38, 7,   0, 66)
 ('14-10-2017',   61, 100,   1, 5,   0, 66)
 ('15-10-2017', 1258, 100,  40, 6,   0, 65)
 ('16-10-2017', 3148, 100, 101, 8,   0, 65)
 ('17-10-2017', 4687, 100, 152, 5,   0, 65)
 ('18-10-2017', 4732, 300, 150, 6, 500, 65)
 ('19-10-2017', 3519, 100, 113, 7,   0, 65)
 ('20-10-2017', 1580, 100,  49, 5,   0, 65)
 ('21-10-2017', 2822, 100,  86, 6,   0, 65)
 ('22-10-2017',  181, 100,   6, 8,   0, 65)
 ('23-10-2017', 3158, 200,  99, 5,   0, 65)
 ('24-10-2017', 4383, 200, 143, 4,   0, 64)
 ('25-10-2017', 3881, 200, 125, 5,   0, 64)]
